### PR TITLE
Logo and Favicon New

### PR DESCRIPTION
**Pull request by Xiphunon**
Folder with logo and favicon

### CODE REVIEW

**Comment by Xiphunon** [comment]
suggest removing _logo_1.svg_ from root folder, and using _z_images_ folder for resources.
(z for folder to be last on the list)

**Comment by MaanooAk** [comment]
@Xiphunon I think we can make folder named `data` and put all kinds of assets there, so we move your folder to `data/images` or `data/icons`

**Comment by Xiphunon** [comment]
@MaanooAk I created a ```data/images folder```. Should ```data``` folder be in root, or inside ```genume``` folder?

**Comment by MaanooAk** [comment]
@Xiphunon root, `genume` should be only for python code

**Comment by Sima214** [comment]
@xlxs4 logo was created here.

**Pull request merged**
