### PR TITLE
Refresh button update.

### PR DESCRIPTION
**Pull request by DrMerfy**
Some noticeable changes:

- Added a refresh button
- Changed the color pallet
- Made the tabs change color when they are selected
- The whole GUI color pallet can now be configured using only CSS.

genume

### CODE REVIEW

**Comment by MaanooAk** [comment]
Min height and height in the css is a new feature of gtk (= its not supported widely)

```
  File "/home/maanoo/Documents/Workspace/tmp1525944998/genume/view/main.py", line 175, in load_css
    style_provider.load_from_data(css_data)
GLib.Error: gtk-css-provider-error-quark: <data>:4:14'min-height' is not a valid property name (3)
```

I suggest you move them from the css to the code

**Comment by MaanooAk** [comment]
By removing the css entries about the size, it works ok.
But, at the start and after a refrsh no tab is highlighted.

**Comment by drazioti** [comment]
me too, in python 3.5
GLib.Error: gtk-css-provider-error-quark: <data>:21:14'min-height' is not a valid property name (3)

**Comment by DrMerfy** [comment]
As pointed by @MaanooAk it's not a python issue, it's a Gtk version issue. Removed the size from the CSS but planning on finding a way to re-implement it. The highlighting is a good point and it was fixed.

**Comment by drazioti** [comment]
nope.
File "/home/draziotis/Documents/genume/genume/view/main.py", line 124, in generate_main_view
    main_view.set_overlay_pass_through(refresh_button, True)
AttributeError: 'Overlay' object has no attribute 'set_overlay_pass_through'

**Comment by DrMerfy** [comment]
The GtkOverlay.set_overlay_pass_through(...) exists in the Gtk package since 3.18 : https://developer.gnome.org/gtk3/stable/GtkOverlay.html . What Gtk version are you on? I'll work on a solution to support older gtk versions, but with a different interface. For the time being, are you able to upgrade your Gtk?

**Pull request merged**
