### PR TITLE
Contributing/README.md

### PR DESCRIPTION
**Pull request by xlxs4**
Visit #82 for an overview of the upcoming documentation-related changes.

**[Done]**

This **PR** adds the **_core_ documentation support** for the Genume repository.
This **_core_** consists of:

----
**0.** **_CONTRIBUTING.md_**
[genume/.github/CONTRIBUTING.md]

**1.** **_README.md_**
[genume/README.md]

In addition to this core files infrastructure, the _following_ are also added:

- **_SUPPORT.md_**
[genume/.github/SUPPORT.md]

- **_git_ subdir** featuring:
  * **README.md** [genume/docs/git/README.md]
  * **basics.md** [genume/docs/git/basics.md]

- **_learning Genume_ subdir** feauturing:
(TODO)
  * **README.md** [genume/docs/learning-genume/README.md]
  * **genume-beginners-guide.md** [genume/docs/learning-genume/genume-beginners-guide.md]
  * **create-genume-scripts.md** [genume/docs/learning-genume/create-genume-scripts.md] 
  * **advanced-genume-options.md** [genume/docs/learning-genume/advanced-genume-options.md] 

- **updates on _script's README.md_** [genume/scripts/README.md]

Below follows a more descriptive writedown of the files to be added:

--------

- .github/**CONTRIBUTING.md**:
This is the contribution guidelines markdown file, featuring links to:
  * the git subdir in the docs folder, serving as an overall guideline on how to use git as a VC in order to successfully contribute to the project, along with a couple supplementary useful relevant links
  * details on how to contribute to issues and labels configuration
  * details on how to contribute to documentation, and a couple useful formatting tools
  * details on how to contribute to the actual code; links to building Genume, finding/creating an issue, forks/PRs, PR life cycle and overall workflow, common practices

- .github/**SUPPORT.md**:
This is the markdown file meant to serve as a means of helping/redirecting the user.

- **README.md**:
Our README markdown file got updated with some word spice and some md syntax sugar added, as well as links to the contributing guidelines, the support section, and, finally, a licensing, feautures, installation, building the repo, enviroment and git tabs

- **docs/git**:
This new sub-directory features two markdown files: 
A _README.md_ and a _basics.md_.
  * README.md provides the user with information on how to work with the Genume repository: `git clone`, forks, branches, syncing, complex scenarios coverup, useful links and recommended git configurations.
  * basics.md serves as a mostly introductory markdown on git/github as a Version Control utility: Installing git, useful git tutorials and tips on security (authentication).

- **docs/learning-genume**:
This new sub-directory features four markdown files and is yet to be implemented:
_README.md_, _advanced-genume-options.md_, _create-genume-scripts.md_ and _genume-beginners-guide.md_.

- **scripts/README.md**:
This markdown already existed, it just got a revamp and a couple of sections added:
_Best Practices_,  _Coding Conventions_ and _Commenting Conventions_

Note that docs/learning-genume is not finalized. The markdown files were initialized so as to have functional links elsewhere (e.g README.md/CONTRIBUTING.md). I will update them in a future PR, separately.
====

### CODE REVIEW

**Comment by Sima214** [comment]
Just note that genume doesn't support the non-posix os(aka win32)

**Comment by xlxs4** [comment]
@Sima214 Review when you can.

**Comment by xlxs4** [comment]
Markdown is just fine.
Genume specific information should be in docs such as learning genume, bugfixing, generating logs, writing scripts etc; not in the general documentation.
You could also add specific contributing guidelines; be my guest.

**Comment by Sima214** [comment]
I cannot merge this, personally.

**Comment by Sima214** [comment]
I find what you propose confusing. Documentation about genume should be specific to genume. I cannot really understand why we should mix generic documentation about how open source software works.

Also about the formatting:
Markdown is kind of special because it will always output something.
If I ignore that you didn't follow the styling already used in the existing markdown files ([markdownlint defaults with no line length limit](https://github.com/markdownlint/markdownlint)) you still have a header which contains url unsafe symbols and also links to images are not relative where possible.
These may cause rendering inconsistencies when using non-github markdown renderers. Also that thing with the images will not reflect any changes made locally to them.

Finally I don't agree with what you are adding, so I cannot merge this pull request.

**Comment by Sima214** [comment]
Oops, didn't know it depended on the docs branch.

**Pull request closed without merging**
