### PR TITLE
Network Adapters

### PR DESCRIPTION
**Pull request by Winner5001**
Added script that detects wireless and ethernet adapters.

### CODE REVIEW

**Comment by drazioti** [comment]
what is the summary section ? Is it necessary?

**Comment by Winner5001** [comment]
It contains the most important information for a computer gathered in a single tab. Generally is good practice to have the summary of something in the beginning and if the user wants to learn more he can always visit the other tabs.

**Comment by drazioti** [comment]
> It contains the most important information for a computer gathered in a single tab. Generally is good practice to have the summary of something in the beginning and if the user wants to learn more he can always visit the other tabs.

In python3.5 (my distro) Summary tab is null

**Comment by Sima214** [comment]
> In python3.5 (my distro) Summary tab is empty.

The file is not set as executable.

**Comment by xlxs4** [comment]
The summary tab just adds on redundancy. This information is already easily accessible and correctly sorted.

**Comment by drazioti** [comment]
@Winner5001  I suggest you, to remove summary and leave network as is.

**Comment by Sima214** [comment]
Merged, but gitbub did not recognize because I deleted some of your commits.

**Pull request closed without merging**
