### PR TITLE
[WIP] Setup.py support

### PR DESCRIPTION
**Pull request by teogramm**
I have added support for setup.py. To do that I had to move the scripts and data directories inside the module directory. I could not find any other way. Some changes to the way paths are handled inside the code, were also required.

### CODE REVIEW

**Comment by teogramm** [comment]
Fixes #22

**Comment by teogramm** [comment]
Just noticed that this breaks the about tab as git does not work in the module directory

**Comment by drazioti** [comment]
after python setup.py install got  many errors. add [wip], since your pull request is not ready

**Comment by Sima214** [comment]
Depends on #60

**Comment by teogramm** [comment]
OK. I am going to wait for other improvements and changes to the code to be made and I am going to make another attempt then.

**Pull request closed without merging**
