### PR TITLE
Adding memory info

### PR DESCRIPTION
**Pull request by KingPachirisu**
Will contain information(space,hardware info) about Ram,Caches,Secondary Memory and possibly Registers.

### CODE REVIEW

**Comment by KingPachirisu** [comment]
ready to be merged

**Comment by KingPachirisu** [comment]
could not find info regarding registers.

**Comment by MaanooAk** [comment]
Your output format cannot be parsed. Check the [protocol documentation](https://github.com/CSD-FOSS-Team/genume/blob/master/scripts/PROTOCOL.md#creating-entries)

Also you can add the `-quiet` flag (`lshw -quiet`) for cleaner output and you should probably delete the file you create after you parse it.

**Comment by KingPachirisu** [comment]
done!thanks for the feedback.

**Comment by KingPachirisu** [comment]
ye i knew about that.i will be fixing it on the future.for now merge this if you want.

**Comment by MaanooAk** [comment]
I will merge this, and then i will disable the cache.sh because it causes a crash as is, (also I need to squash it because you have a merge commit)

**Pull request merged**
